In [3]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import OneHotEncoder
from sklearn.model_selection import train_test_split
import warnings
warnings.simplefilter("ignore")

In [9]:
pd.set_option("display.max_columns", None)
pd.set_option("display.max_rows", None)
pd.set_option("display.width", 500)

In [7]:
def load():
    data = pd.read_csv("C:/Users/Kadir/Desktop/ecommerce_user_behavior/data/raw/ecommerce_user_behavior_8000.csv")
    return data
df = load()

In [8]:
df.head()

   user_id   age  gender  ... avg_session_time  bounce_rate  purchase
0      1.0  56.0  Female  ...             6.97        28.18       1.0
1      2.0  46.0    Male  ...            19.17        86.73       1.0
2      3.0  32.0  Female  ...             8.87        83.09       1.0
3      4.0  25.0  Female  ...              NaN        79.03       1.0
4      5.0  38.0  Female  ...            18.15        55.35       1.0

[5 rows x 14 columns]

### Shapes & Columns

In [11]:
print(f"Row numbers: {df.shape[0]}")
print(f"Column numbers: {df.shape[1]}")
print()
print("Columns: ")
for col in df.columns:
    print(f"  - {col}")

Row numbers: 8000
Column numbers: 14

Columns:
  - user_id
  - age
  - gender
  - device_type
  - time_on_site
  - pages_viewed
  - previous_purchases
  - cart_items
  - discount_seen
  - ad_clicked
  - returning_user
  - avg_session_time
  - bounce_rate
  - purchase

### Dtypes

In [12]:
df.dtypes

user_id               float64
age                   float64
gender                    str
device_type               str
time_on_site          float64
pages_viewed          float64
previous_purchases    float64
cart_items            float64
discount_seen         float64
ad_clicked            float64
returning_user        float64
avg_session_time      float64
bounce_rate           float64
purchase              float64
dtype: object

In [13]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 8000 entries, 0 to 7999
Data columns (total 14 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   user_id             7840 non-null   float64
 1   age                 7840 non-null   float64
 2   gender              7840 non-null   str
 3   device_type         7840 non-null   str
 4   time_on_site        7840 non-null   float64
 5   pages_viewed        7840 non-null   float64
 6   previous_purchases  7840 non-null   float64
 7   cart_items          7840 non-null   float64
 8   discount_seen       7840 non-null   float64
 9   ad_clicked          7840 non-null   float64
 10  returning_user      7840 non-null   float64
 11  avg_session_time    7840 non-null   float64
 12  bounce_rate         7840 non-null   float64
 13  purchase            7840 non-null   float64
dtypes: float64(12), str(2)
memory usage: 875.1 KB

### Base fundamentals

In [16]:
df.describe()

           user_id          age  time_on_site  pages_viewed  previous_purchases   cart_items  discount_seen   ad_clicked  returning_user  avg_session_time  bounce_rate     purchase
count  7840.000000  7840.000000   7840.000000   7840.000000         7840.000000  7840.000000    7840.000000  7840.000000     7840.000000       7840.000000  7840.000000  7840.000000
mean   4003.135077    38.595791     15.714673      9.970026            6.964158     4.530230       0.502551     0.502296        0.509439         15.794999    49.924402     0.998342
std    2307.898984    12.033928      8.362764      5.425485            4.281117     2.865814       0.500025     0.500027        0.499943          9.864556    29.137449     0.040689
min       1.000000    18.000000      1.000000      1.000000            0.000000     0.000000       0.000000     0.000000        0.000000          0.570000     0.010000     0.000000
25%    2011.750000    28.000000      8.520000      5.000000            3.000000     2.000000       0.000000     0.000000        0.000000          7.750000    24.677500     1.000000
50%    3998.000000    39.000000     15.740000     10.000000            7.000000     5.000000       1.000000     1.000000        1.000000         14.300000    49.500000     1.000000
75%    6001.250000    49.000000     22.880000     15.000000           11.000000     7.000000       1.000000     1.000000        1.000000         22.392500    75.990000     1.000000
max    8000.000000    59.000000     30.000000     19.000000           14.000000     9.000000       1.000000     1.000000        1.000000         44.750000    99.970000     1.000000

### Missing value analysis

In [23]:
null_count = df.isnull().sum()
null_pct = (null_count / len(df) * 100).round(2)

null_df = pd.DataFrame({
    "Missing value ": null_count, 
    "Missing value %": null_pct
    })

null_df = null_df[null_df["Missing value "] > 0].sort_values("Missing value %", ascending=False)

print("Columns containing missing values: " )
null_df

Columns containing missing values:

                    Missing value   Missing value %
user_id                        160              2.0
age                            160              2.0
gender                         160              2.0
device_type                    160              2.0
time_on_site                   160              2.0
pages_viewed                   160              2.0
previous_purchases             160              2.0
cart_items                     160              2.0
discount_seen                  160              2.0
ad_clicked                     160              2.0
returning_user                 160              2.0
avg_session_time               160              2.0
bounce_rate                    160              2.0
purchase                       160              2.0